---
- name:  kubernetes deployment
  hosts: all
  become: yes
  roles:
    - common

- name: master node configuration
  hosts: masters
  become: yes
  roles:
    - master

- name: master node configuration
  hosts: workers
  become: yes
  roles:
    - worker
